[package]
name = "phosphor-icons-playground"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = { version = "0.8.2", features = ["csr"] }
phosphor-leptos = { git = "https://github.com/flowi/phosphor-leptos", branch = "update-to-leptos-0-8" }
